site_name: Pybot
nav:
  - La documentation de la bibliothèque:
    - introduction: index.md
    - chapitre 1 - Un premier programme: chap1.md
    - chapitre 2 - Une boucle et des évènements: chap2.md
    - chapitre 3 - Des boutons et des couleurs.: chap3.md
    - chapitre 4 - Prendre une photo avec une caméra et appliquer des filtres.: chap4.md
    - chapitre 5 - Reconnaissance d'un élève avec sa carte.: chap5.md
    - chapitre 6 - Parler au robot.: chap6.md
    - chapitre 6.5 - Zone de texte / Entrée Utilisateur : chap6.5.md
    - chapitre 7 - Écouter le robot.: chap7.md
    - chapitre 8 - Le visage et les émotions du robot.: chap8.md
    - Utiliser l'administration web: admin.md
    - Référence complète: ref.md
  - Utiliser la bibliothèque:
    - Apprendre le Python: python.md
    - Installer et utiliser Pybot: config.md
    - Configurer le raspberry pi: rpi.md
  - Développer la bibliothèque:
    - Contribuer au projet: contribute.md
    - Progression du projet: roadmap.md
    - Mettre à jour la documentation: doc.md

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
    admonition:
      note: material/robot-love-outline
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair
  features:
    - navigation.expand
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  