site_name: La bibliothèque pybot 
nav:
  - La documentation de Pybot: index.md
  - Installer et utiliser Pybot: config.md
  - Apprendre le Python: python.md
  - Contribuer au projet: contribute.md
  - Progression du projet: roadmap.md

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences