site_name: La documentation de la bibliothèque Pybot 
nav:
  - Pybot - introduction: index.md
  - Pybot - chapitre 1 - Un premier programme: chap1.md
  - Pybot - chapitre 2 - Une boucle et des évènements: chap2.md
  - Pybot - chapitre 3 - ...: chap3.md
  - Pybot - chapitre 4 - ...: chap4.md
  - Pybot - chapitre 5 - ...: chap5.md
  - Pybot - chapitre 6 - ...: chap6.md
  - Pybot - chapitre 7 - ...: chap7.md
  - Pybot - chapitre 8 - ...: chap8.md
  - Apprendre le Python: python.md
  - Installer et utiliser Pybot: config.md
  - Dev - Contribuer au projet: contribute.md
  - Dev - Progression du projet: roadmap.md

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
    admonition:
      note: material/robot-love-outline
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences