site_name: Pybot
nav:
  - La documentation de la bibliothèque:
    - Introduction: index.md
    - Informations générales sur le Python: general.md
    - Module Robot: module_robot.md
    - Module Fenêtre - Window : module_window.md
    - Les Boutons - Buttons : button.md
    - Les Zones de texte - Text_area : text_area.md
    - Module Caméra - Camera : module_camera.md
    - Module IA - AI : module_ai.md
    - Module Utilisateur - User : module_user.md
    - Module Audio - Audio : module_audio.md
    - Utiliser l'administration web: admin.md
    - Référence complète: ref.md
  - Utiliser la bibliothèque:
    - Apprendre le Python: python.md
    - Installer et utiliser Pybot: config.md
    - Configurer le raspberry pi: rpi.md
  - Développer la bibliothèque:
    - Contribuer au projet: contribute.md
    - Progression du projet: roadmap.md
    - Mettre à jour la documentation: doc.md

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
    admonition:
      note: material/robot-love-outline
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair
  features:
    - navigation.expand
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  